Ft sugerencias
Campus-Connect-PUJ/campus-connect pull request #34
Opened 2021-04-19 23:10 UTC by Laura-Mora

Ya están las reseñas, se envía info al back de los formularios y reseñas, los formularios se activan con un botón en las respectivas pantallas

2021-04-19 23:51 UTC, dhasane requested changes

2021-04-19 23:51 UTC, dhasane commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +      {} // TODO
Aqui haria falta enviar el objeto, no?

2021-04-19 23:51 UTC, dhasane commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +    const url = `${environment.baseUrl}/usuario/${id}/resenha_restaurante/${id_res}/${calificacion}`;
este id es del usuario?

2021-04-19 23:51 UTC, dhasane commented on src/app/grupos-estudiantiles/reco-grupos/datos-grupo/datos-grupo.page.ts
> +      this.puntajeAsig, this.usuario.id,this.grupoSelect.id
esto esta dando error ya que la definicion es distinta

2021-04-20 00:09 UTC, kamilo2299 commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +      {} // TODO
Los datos que se pasan van en el url. Y ese método post si o si necesita algo, por lo que se envía eso vacío

2021-04-20 00:09 UTC, kamilo2299 commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +    const url = `${environment.baseUrl}/usuario/${id}/resenha_restaurante/${id_res}/${calificacion}`;
Yep

2021-04-20 00:16 UTC, dhasane commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +      {} // TODO
no seria mejor enviarlos dentro de un objeto y recibirlos con un wrapper?

2021-04-20 00:18 UTC, dhasane commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +    const url = `${environment.baseUrl}/usuario/${id}/resenha_restaurante/${id_res}/${calificacion}`;
ya que el usuario es el unico que puede crear sus propias reseñas, tendría más sentido aprovechar el token e identificar al usuario en el servidor con AuthenticationPrincipal.
Con eso se podría quitar ese id, ya que no sería necesario.

2021-04-20 00:18 UTC, kamilo2299 commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +      {} // TODO
Era una de las dos opciones. Esta era la primera y la rápida. Luego se puede cambiar. 

Igual, aun falta probarlo por que posiblemente toque hacer cambios en las url o mirar como se debe de conectar

2021-04-20 00:52 UTC, dhasane commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +      {} // TODO
Valido.
Podria ser preferible el wrapper, pero si de momento funciona, esta bien.

2021-04-20 18:34 UTC, dhasane requested changes

2021-04-20 18:34 UTC, dhasane commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +        "resenha": resenia
esto tambien deberia ser solo con las estrellas

2021-04-20 18:39 UTC, Laura-Mora commented on src/app/Model/UsuarioGeneral/usuario-general.service.ts
> +        "resenha": resenia
Listo ya se cambio

2021-04-20 18:40 UTC, dhasane approved these changes

2021-04-20 18:40 UTC, merged