Ft fix seleccion rutas
Campus-Connect-PUJ/campus-connect pull request #41
Opened 2021-04-26 02:42 UTC by kstro96

Rutas generadas teniendo en cuenta los reportes de los usuarios

2021-04-26 21:22 UTC, dhasane commented
falta recalcular rutas

2021-04-26 21:22 UTC, dhasane requested changes
Falta recalcular rutas

2021-04-26 21:22 UTC, dhasane commented on package.json
> +    "start": "ng serve --proxy-config proxy.conf.json",
el proxy sigue siendo necesario despues de hacer la correccion del token?

2021-04-26 22:40 UTC, kstro96 commented on package.json
> +    "start": "ng serve --proxy-config proxy.conf.json",
En mi compu ya funciona sin eso ya lo quite

2021-04-26 22:40 UTC, kstro96 commented
Cambios pedidos por @dhasane realizados. Se probaron y parece que funcionan de acuerdo a lo descrito.

2021-04-27 00:22 UTC, dhasane commented
Sigue haciendo falta el recalcular rutas.

2021-04-27 18:35 UTC, kamilo2299 approved these changes
Sirve bien. Si acaso seria útil que aparecía el por que no se genera la ruta por un sitio(tipo mostrar las eventualidades de la ruta normal, aunque no se si se pueda realizar fácilmente)

2021-04-27 18:52 UTC, dhasane commented
si seria chevere que se mostraran las eventualidades en la ruta, como para que el usuario entendiera por que lo manda por una ruta especifica, pero eso ya podria ser dejado para despues.

2021-04-27 21:18 UTC, dhasane approved these changes

2021-04-27 21:19 UTC, merged